package:
  name: audio-spectracli
  version: "4.0.1"

source:
  git_url: https://github.com/AdityaSeth777/Audio-SpectraCLI.git
  git_tag: v4.0.0  # Replace with the tag or branch name you want to build from
  
build:
  noarch: python
  script: |
    pip install sounddevice
    python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - numpy
    - matplotlib
    - pyqt5-sip
    - scipy
    - pyaudio
    - tabulate

test:
  imports:
    - Audio_SpectraCLI

about:
  home: https://github.com/AdityaSeth777/Audio-SpectraCLI
  license: Apache License 2.0
  summary: "A command-line tool for real-time audio spectrum visualization."
  description: |
    Audio-SpectraCLI is a tool that provides real-time audio spectrum analysis using a command-line interface.

extra:
  recipe-maintainers:
    - AdityaSeth777
