name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GREETINGS_TOKEN }}
          issue-message: "Greetings and Thank you for submitting the issue ! This message is automated, in case you are wondering. I will get back to you on this."
          pr-message: "Congratulations on submitting your PR ! It will be merged if it passes the requirements. Thanks."
